import type { Theme } from "../backend";
import {
  BorderStyle,
  Document,
  HeadingLevel,
  Packer,
  Paragraph,
  Table,
  TableCell,
  TableRow,
  TextRun,
  WidthType,
} from "./stubs/docx";
import { jsPDF } from "./stubs/jspdf";
import * as XLSX from "./stubs/xlsx";

export interface DocField {
  label: string;
  value: string;
}

export async function generateDOCX(
  title: string,
  fields: DocField[],
  _theme?: Theme,
): Promise<Blob> {
  const noBorder = {
    top: { style: BorderStyle.SINGLE, size: 1, color: "DDDDDD" },
    bottom: { style: BorderStyle.SINGLE, size: 1, color: "DDDDDD" },
    left: { style: BorderStyle.SINGLE, size: 1, color: "DDDDDD" },
    right: { style: BorderStyle.SINGLE, size: 1, color: "DDDDDD" },
  };

  const tableRows = fields.map(
    (f) =>
      new TableRow({
        children: [
          new TableCell({
            borders: noBorder,
            width: { size: 40, type: WidthType.PERCENTAGE },
            children: [
              new Paragraph({
                children: [new TextRun({ text: f.label, bold: true })],
              }),
            ],
          }),
          new TableCell({
            borders: noBorder,
            width: { size: 60, type: WidthType.PERCENTAGE },
            children: [new Paragraph(f.value || "-")],
          }),
        ],
      }),
  );

  const doc = new Document({
    sections: [
      {
        children: [
          new Paragraph({
            text: title,
            heading: HeadingLevel.HEADING_1,
          }),
          new Paragraph({
            children: [
              new TextRun({
                text: `Generated: ${new Date().toLocaleDateString("en-IN")}`,
                italics: true,
                color: "888888",
              }),
            ],
          }),
          new Paragraph({ text: "" }),
          ...(tableRows.length > 0
            ? [
                new Table({
                  rows: tableRows,
                  width: { size: 100, type: WidthType.PERCENTAGE },
                }),
              ]
            : [new Paragraph({ text: "No fields provided." })]),
          new Paragraph({ text: "" }),
          new Paragraph({
            children: [
              new TextRun({
                text: "Generated by BizDox — Professional Trade Document Platform",
                color: "AAAAAA",
                size: 18,
              }),
            ],
          }),
        ],
      },
    ],
  });

  return await Packer.toBlob(doc);
}

export async function generateXLSX(
  title: string,
  fields: DocField[],
): Promise<Blob> {
  const wb = XLSX.utils.book_new();

  const ws1Data = [
    ["BizDox — Trade Document"],
    [title],
    [`Generated: ${new Date().toLocaleDateString("en-IN")}`],
    [""],
    ["Field", "Value"],
    ...fields.map((f) => [f.label, f.value || "-"]),
  ];
  const ws1 = XLSX.utils.aoa_to_sheet(ws1Data);
  ws1["!cols"] = [{ wch: 35 }, { wch: 50 }];
  XLSX.utils.book_append_sheet(wb, ws1, "Document Details");

  const buf = XLSX.write(wb, { type: "array", bookType: "xlsx" });
  return new Blob([buf], {
    type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  });
}

export async function generatePDF(
  title: string,
  fields: DocField[],
  _theme?: Theme,
): Promise<Blob> {
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  doc.setFillColor(31, 111, 67);
  doc.rect(0, 0, 210, 28, "F");
  doc.setFontSize(20);
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.text(title, 15, 18);

  doc.setFontSize(9);
  doc.setTextColor(200, 255, 200);
  doc.setFont("helvetica", "normal");
  doc.text(
    `Generated: ${new Date().toLocaleDateString("en-IN")} | BizDox by SBZ Enterprises`,
    15,
    24,
  );

  let y = 40;
  doc.setTextColor(43, 43, 43);

  fields.forEach((f, i) => {
    if (y > 270) {
      doc.addPage();
      y = 20;
    }

    const rowBg = i % 2 === 0 ? [245, 246, 248] : [255, 255, 255];
    doc.setFillColor(rowBg[0], rowBg[1], rowBg[2]);
    doc.rect(12, y - 5, 186, 9, "F");

    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(31, 111, 67);
    doc.text(f.label, 15, y);

    doc.setFont("helvetica", "normal");
    doc.setTextColor(43, 43, 43);
    const lines = doc.splitTextToSize(f.value || "-", 110);
    doc.text(lines, 90, y);

    y += Math.max(9, lines.length * 5 + 3);
  });

  doc.setFontSize(8);
  doc.setTextColor(180, 180, 180);
  doc.text(
    "Generated by BizDox — Professional Trade Document Platform",
    15,
    287,
  );

  return doc.output("blob");
}

export function downloadBlob(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
