/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PaymentId = IDL.Text;
export const TemplateId = IDL.Text;
export const ThemeId = IDL.Text;
export const UserId = IDL.Principal;
export const Timestamp = IDL.Int;
export const DocumentId = IDL.Text;
export const Document = IDL.Record({
  'status' : IDL.Variant({ 'generated' : IDL.Null, 'draft' : IDL.Null }),
  'title' : IDL.Text,
  'templateId' : TemplateId,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'documentId' : DocumentId,
  'themeId' : ThemeId,
});
export const FieldId = IDL.Text;
export const FormField = IDL.Record({
  'fieldPlaceholder' : IDL.Text,
  'order' : IDL.Nat,
  'templateId' : TemplateId,
  'fieldLabel' : IDL.Text,
  'helpText' : IDL.Text,
  'fieldWidth' : IDL.Nat,
  'visible' : IDL.Bool,
  'required' : IDL.Bool,
  'groupName' : IDL.Text,
  'options' : IDL.Vec(IDL.Text),
  'fieldType' : IDL.Variant({
    'textArea' : IDL.Null,
    'multiSelect' : IDL.Null,
    'numberField' : IDL.Null,
    'textField' : IDL.Null,
    'currency' : IDL.Null,
    'checkbox' : IDL.Null,
    'dateField' : IDL.Null,
    'radio' : IDL.Null,
    'percentage' : IDL.Null,
    'dropdown' : IDL.Null,
  }),
  'defaultValue' : IDL.Opt(IDL.Text),
  'fieldId' : FieldId,
  'condition' : IDL.Opt(
    IDL.Record({ 'conditionField' : IDL.Text, 'conditionValue' : IDL.Text })
  ),
});
export const PlaceholderId = IDL.Text;
export const Placeholder = IDL.Record({
  'token' : IDL.Text,
  'templateId' : TemplateId,
  'description' : IDL.Text,
  'placeholderId' : PlaceholderId,
  'fieldId' : FieldId,
});
export const UserProfile = IDL.Record({
  'id' : UserId,
  'country' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'role' : UserRole,
  'email' : IDL.Text,
  'companyName' : IDL.Text,
  'phone' : IDL.Text,
});
export const Template = IDL.Record({
  'id' : TemplateId,
  'status' : IDL.Bool,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'createdBy' : UserId,
  'commodityType' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
});
export const Theme = IDL.Record({
  'themeName' : IDL.Text,
  'footerStyle' : IDL.Text,
  'primaryColor' : IDL.Text,
  'createdBy' : IDL.Opt(UserId),
  'headerDesign' : IDL.Text,
  'fontFamily' : IDL.Text,
  'secondaryColor' : IDL.Text,
  'tableBorders' : IDL.Bool,
  'themeId' : ThemeId,
  'pageMargins' : IDL.Text,
});
export const ExportId = IDL.Text;
export const Export = IDL.Record({
  'exportId' : ExportId,
  'userId' : UserId,
  'downloadDate' : Timestamp,
  'paymentId' : PaymentId,
  'documentId' : DocumentId,
  'format' : IDL.Variant({
    'pdf' : IDL.Null,
    'docx' : IDL.Null,
    'xlsx' : IDL.Null,
  }),
});
export const Payment = IDL.Record({
  'status' : IDL.Variant({ 'pending' : IDL.Null, 'confirmed' : IDL.Null }),
  'userId' : UserId,
  'createdAt' : Timestamp,
  'currency' : IDL.Text,
  'paymentId' : PaymentId,
  'documentId' : DocumentId,
  'amount' : IDL.Nat,
  'transactionId' : IDL.Opt(IDL.Text),
});
export const DocumentData = IDL.Record({
  'value' : IDL.Text,
  'documentId' : DocumentId,
  'fieldId' : FieldId,
});
export const TemplateSeedStatus = IDL.Record({
  'totalThemes' : IDL.Nat,
  'seededTemplateNames' : IDL.Vec(IDL.Text),
  'totalTemplates' : IDL.Nat,
});
export const TemplateSeedResult = IDL.Record({
  'templatesSkipped' : IDL.Nat,
  'themesCreated' : IDL.Nat,
  'templatesCreated' : IDL.Nat,
  'themesSkipped' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'confirmPayment' : IDL.Func([PaymentId, IDL.Text], [], []),
  'createDocument' : IDL.Func([TemplateId, IDL.Text, ThemeId], [Document], []),
  'createFormField' : IDL.Func(
      [
        TemplateId,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Bool,
        IDL.Opt(IDL.Text),
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
        IDL.Opt(
          IDL.Record({
            'conditionField' : IDL.Text,
            'conditionValue' : IDL.Text,
          })
        ),
      ],
      [FormField],
      [],
    ),
  'createPlaceholder' : IDL.Func(
      [TemplateId, IDL.Text, FieldId, IDL.Text],
      [Placeholder],
      [],
    ),
  'createProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [UserProfile],
      [],
    ),
  'createTemplate' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [Template],
      [],
    ),
  'createTheme' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
        IDL.Text,
      ],
      [Theme],
      [],
    ),
  'deleteDocument' : IDL.Func([DocumentId], [], []),
  'deleteFormField' : IDL.Func([FieldId], [], []),
  'deletePlaceholder' : IDL.Func([PlaceholderId], [], []),
  'deleteTemplate' : IDL.Func([TemplateId], [], []),
  'deleteTheme' : IDL.Func([ThemeId], [], []),
  'demoteToUser' : IDL.Func([UserId], [], []),
  'getActiveTemplates' : IDL.Func([], [IDL.Vec(Template)], ['query']),
  'getAllExports' : IDL.Func([], [IDL.Vec(Export)], ['query']),
  'getAllPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
  'getAllTemplates' : IDL.Func([], [IDL.Vec(Template)], ['query']),
  'getAllThemes' : IDL.Func([], [IDL.Vec(Theme)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getAnalytics' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalUsers' : IDL.Nat,
          'totalRevenue' : IDL.Nat,
          'totalDownloads' : IDL.Nat,
          'totalDocuments' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDocumentData' : IDL.Func(
      [DocumentId],
      [IDL.Vec(DocumentData)],
      ['query'],
    ),
  'getDocumentsByUser' : IDL.Func([UserId], [IDL.Vec(Document)], ['query']),
  'getExportsByUser' : IDL.Func([UserId], [IDL.Vec(Export)], ['query']),
  'getFieldsForTemplate' : IDL.Func(
      [TemplateId],
      [IDL.Vec(FormField)],
      ['query'],
    ),
  'getPaymentsByUser' : IDL.Func([UserId], [IDL.Vec(Payment)], ['query']),
  'getPlaceholdersForTemplate' : IDL.Func(
      [TemplateId],
      [IDL.Vec(Placeholder)],
      ['query'],
    ),
  'getSeedStatus' : IDL.Func([], [TemplateSeedStatus], ['query']),
  'getTemplate' : IDL.Func([TemplateId], [IDL.Opt(Template)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'promoteToAdmin' : IDL.Func([UserId], [], []),
  'recordExport' : IDL.Func(
      [
        DocumentId,
        IDL.Variant({ 'pdf' : IDL.Null, 'docx' : IDL.Null, 'xlsx' : IDL.Null }),
        PaymentId,
      ],
      [Export],
      [],
    ),
  'recordPayment' : IDL.Func([DocumentId, IDL.Nat, IDL.Text], [Payment], []),
  'saveCallerUserProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'saveDocumentData' : IDL.Func([DocumentId, FieldId, IDL.Text], [], []),
  'seedStandardTemplates' : IDL.Func([], [TemplateSeedResult], []),
  'updateDocument' : IDL.Func(
      [
        DocumentId,
        IDL.Text,
        ThemeId,
        IDL.Variant({ 'generated' : IDL.Null, 'draft' : IDL.Null }),
      ],
      [],
      [],
    ),
  'updateFormField' : IDL.Func(
      [
        FieldId,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Bool,
        IDL.Opt(IDL.Text),
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
        IDL.Opt(
          IDL.Record({
            'conditionField' : IDL.Text,
            'conditionValue' : IDL.Text,
          })
        ),
      ],
      [],
      [],
    ),
  'updatePlaceholder' : IDL.Func(
      [PlaceholderId, IDL.Text, FieldId, IDL.Text],
      [],
      [],
    ),
  'updateTemplate' : IDL.Func(
      [TemplateId, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [],
      [],
    ),
  'updateTheme' : IDL.Func(
      [
        ThemeId,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
        IDL.Text,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PaymentId = IDL.Text;
  const TemplateId = IDL.Text;
  const ThemeId = IDL.Text;
  const UserId = IDL.Principal;
  const Timestamp = IDL.Int;
  const DocumentId = IDL.Text;
  const Document = IDL.Record({
    'status' : IDL.Variant({ 'generated' : IDL.Null, 'draft' : IDL.Null }),
    'title' : IDL.Text,
    'templateId' : TemplateId,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'updatedAt' : Timestamp,
    'documentId' : DocumentId,
    'themeId' : ThemeId,
  });
  const FieldId = IDL.Text;
  const FormField = IDL.Record({
    'fieldPlaceholder' : IDL.Text,
    'order' : IDL.Nat,
    'templateId' : TemplateId,
    'fieldLabel' : IDL.Text,
    'helpText' : IDL.Text,
    'fieldWidth' : IDL.Nat,
    'visible' : IDL.Bool,
    'required' : IDL.Bool,
    'groupName' : IDL.Text,
    'options' : IDL.Vec(IDL.Text),
    'fieldType' : IDL.Variant({
      'textArea' : IDL.Null,
      'multiSelect' : IDL.Null,
      'numberField' : IDL.Null,
      'textField' : IDL.Null,
      'currency' : IDL.Null,
      'checkbox' : IDL.Null,
      'dateField' : IDL.Null,
      'radio' : IDL.Null,
      'percentage' : IDL.Null,
      'dropdown' : IDL.Null,
    }),
    'defaultValue' : IDL.Opt(IDL.Text),
    'fieldId' : FieldId,
    'condition' : IDL.Opt(
      IDL.Record({ 'conditionField' : IDL.Text, 'conditionValue' : IDL.Text })
    ),
  });
  const PlaceholderId = IDL.Text;
  const Placeholder = IDL.Record({
    'token' : IDL.Text,
    'templateId' : TemplateId,
    'description' : IDL.Text,
    'placeholderId' : PlaceholderId,
    'fieldId' : FieldId,
  });
  const UserProfile = IDL.Record({
    'id' : UserId,
    'country' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'role' : UserRole,
    'email' : IDL.Text,
    'companyName' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Template = IDL.Record({
    'id' : TemplateId,
    'status' : IDL.Bool,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'createdBy' : UserId,
    'commodityType' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
  });
  const Theme = IDL.Record({
    'themeName' : IDL.Text,
    'footerStyle' : IDL.Text,
    'primaryColor' : IDL.Text,
    'createdBy' : IDL.Opt(UserId),
    'headerDesign' : IDL.Text,
    'fontFamily' : IDL.Text,
    'secondaryColor' : IDL.Text,
    'tableBorders' : IDL.Bool,
    'themeId' : ThemeId,
    'pageMargins' : IDL.Text,
  });
  const ExportId = IDL.Text;
  const Export = IDL.Record({
    'exportId' : ExportId,
    'userId' : UserId,
    'downloadDate' : Timestamp,
    'paymentId' : PaymentId,
    'documentId' : DocumentId,
    'format' : IDL.Variant({
      'pdf' : IDL.Null,
      'docx' : IDL.Null,
      'xlsx' : IDL.Null,
    }),
  });
  const Payment = IDL.Record({
    'status' : IDL.Variant({ 'pending' : IDL.Null, 'confirmed' : IDL.Null }),
    'userId' : UserId,
    'createdAt' : Timestamp,
    'currency' : IDL.Text,
    'paymentId' : PaymentId,
    'documentId' : DocumentId,
    'amount' : IDL.Nat,
    'transactionId' : IDL.Opt(IDL.Text),
  });
  const DocumentData = IDL.Record({
    'value' : IDL.Text,
    'documentId' : DocumentId,
    'fieldId' : FieldId,
  });
  const TemplateSeedStatus = IDL.Record({
    'totalThemes' : IDL.Nat,
    'seededTemplateNames' : IDL.Vec(IDL.Text),
    'totalTemplates' : IDL.Nat,
  });
  const TemplateSeedResult = IDL.Record({
    'templatesSkipped' : IDL.Nat,
    'themesCreated' : IDL.Nat,
    'templatesCreated' : IDL.Nat,
    'themesSkipped' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'confirmPayment' : IDL.Func([PaymentId, IDL.Text], [], []),
    'createDocument' : IDL.Func(
        [TemplateId, IDL.Text, ThemeId],
        [Document],
        [],
      ),
    'createFormField' : IDL.Func(
        [
          TemplateId,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Bool,
          IDL.Opt(IDL.Text),
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
          IDL.Opt(
            IDL.Record({
              'conditionField' : IDL.Text,
              'conditionValue' : IDL.Text,
            })
          ),
        ],
        [FormField],
        [],
      ),
    'createPlaceholder' : IDL.Func(
        [TemplateId, IDL.Text, FieldId, IDL.Text],
        [Placeholder],
        [],
      ),
    'createProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [UserProfile],
        [],
      ),
    'createTemplate' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [Template],
        [],
      ),
    'createTheme' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
          IDL.Text,
        ],
        [Theme],
        [],
      ),
    'deleteDocument' : IDL.Func([DocumentId], [], []),
    'deleteFormField' : IDL.Func([FieldId], [], []),
    'deletePlaceholder' : IDL.Func([PlaceholderId], [], []),
    'deleteTemplate' : IDL.Func([TemplateId], [], []),
    'deleteTheme' : IDL.Func([ThemeId], [], []),
    'demoteToUser' : IDL.Func([UserId], [], []),
    'getActiveTemplates' : IDL.Func([], [IDL.Vec(Template)], ['query']),
    'getAllExports' : IDL.Func([], [IDL.Vec(Export)], ['query']),
    'getAllPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
    'getAllTemplates' : IDL.Func([], [IDL.Vec(Template)], ['query']),
    'getAllThemes' : IDL.Func([], [IDL.Vec(Theme)], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getAnalytics' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalUsers' : IDL.Nat,
            'totalRevenue' : IDL.Nat,
            'totalDownloads' : IDL.Nat,
            'totalDocuments' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDocumentData' : IDL.Func(
        [DocumentId],
        [IDL.Vec(DocumentData)],
        ['query'],
      ),
    'getDocumentsByUser' : IDL.Func([UserId], [IDL.Vec(Document)], ['query']),
    'getExportsByUser' : IDL.Func([UserId], [IDL.Vec(Export)], ['query']),
    'getFieldsForTemplate' : IDL.Func(
        [TemplateId],
        [IDL.Vec(FormField)],
        ['query'],
      ),
    'getPaymentsByUser' : IDL.Func([UserId], [IDL.Vec(Payment)], ['query']),
    'getPlaceholdersForTemplate' : IDL.Func(
        [TemplateId],
        [IDL.Vec(Placeholder)],
        ['query'],
      ),
    'getSeedStatus' : IDL.Func([], [TemplateSeedStatus], ['query']),
    'getTemplate' : IDL.Func([TemplateId], [IDL.Opt(Template)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'promoteToAdmin' : IDL.Func([UserId], [], []),
    'recordExport' : IDL.Func(
        [
          DocumentId,
          IDL.Variant({
            'pdf' : IDL.Null,
            'docx' : IDL.Null,
            'xlsx' : IDL.Null,
          }),
          PaymentId,
        ],
        [Export],
        [],
      ),
    'recordPayment' : IDL.Func([DocumentId, IDL.Nat, IDL.Text], [Payment], []),
    'saveCallerUserProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'saveDocumentData' : IDL.Func([DocumentId, FieldId, IDL.Text], [], []),
    'seedStandardTemplates' : IDL.Func([], [TemplateSeedResult], []),
    'updateDocument' : IDL.Func(
        [
          DocumentId,
          IDL.Text,
          ThemeId,
          IDL.Variant({ 'generated' : IDL.Null, 'draft' : IDL.Null }),
        ],
        [],
        [],
      ),
    'updateFormField' : IDL.Func(
        [
          FieldId,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Bool,
          IDL.Opt(IDL.Text),
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
          IDL.Opt(
            IDL.Record({
              'conditionField' : IDL.Text,
              'conditionValue' : IDL.Text,
            })
          ),
        ],
        [],
        [],
      ),
    'updatePlaceholder' : IDL.Func(
        [PlaceholderId, IDL.Text, FieldId, IDL.Text],
        [],
        [],
      ),
    'updateTemplate' : IDL.Func(
        [TemplateId, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [],
        [],
      ),
    'updateTheme' : IDL.Func(
        [
          ThemeId,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
          IDL.Text,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };