/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Document {
  'status' : { 'generated' : null } |
    { 'draft' : null },
  'title' : string,
  'templateId' : TemplateId,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'documentId' : DocumentId,
  'themeId' : ThemeId,
}
export interface DocumentData {
  'value' : string,
  'documentId' : DocumentId,
  'fieldId' : FieldId,
}
export type DocumentId = string;
export interface Export {
  'exportId' : ExportId,
  'userId' : UserId,
  'downloadDate' : Timestamp,
  'paymentId' : PaymentId,
  'documentId' : DocumentId,
  'format' : { 'pdf' : null } |
    { 'docx' : null } |
    { 'xlsx' : null },
}
export type ExportId = string;
export type FieldId = string;
export interface FormField {
  'fieldPlaceholder' : string,
  'order' : bigint,
  'templateId' : TemplateId,
  'fieldLabel' : string,
  'helpText' : string,
  'fieldWidth' : bigint,
  'visible' : boolean,
  'required' : boolean,
  'groupName' : string,
  'options' : Array<string>,
  'fieldType' : { 'textArea' : null } |
    { 'multiSelect' : null } |
    { 'numberField' : null } |
    { 'textField' : null } |
    { 'currency' : null } |
    { 'checkbox' : null } |
    { 'dateField' : null } |
    { 'radio' : null } |
    { 'percentage' : null } |
    { 'dropdown' : null },
  'defaultValue' : [] | [string],
  'fieldId' : FieldId,
  'condition' : [] | [{ 'conditionField' : string, 'conditionValue' : string }],
}
export interface Payment {
  'status' : { 'pending' : null } |
    { 'confirmed' : null },
  'userId' : UserId,
  'createdAt' : Timestamp,
  'currency' : string,
  'paymentId' : PaymentId,
  'documentId' : DocumentId,
  'amount' : bigint,
  'transactionId' : [] | [string],
}
export type PaymentId = string;
export interface Placeholder {
  'token' : string,
  'templateId' : TemplateId,
  'description' : string,
  'placeholderId' : PlaceholderId,
  'fieldId' : FieldId,
}
export type PlaceholderId = string;
export interface Template {
  'id' : TemplateId,
  'status' : boolean,
  'name' : string,
  'createdAt' : Timestamp,
  'createdBy' : UserId,
  'commodityType' : string,
  'description' : string,
  'category' : string,
}
export type TemplateId = string;
export interface TemplateSeedResult {
  'templatesSkipped' : bigint,
  'themesCreated' : bigint,
  'templatesCreated' : bigint,
  'themesSkipped' : bigint,
}
export interface TemplateSeedStatus {
  'totalThemes' : bigint,
  'seededTemplateNames' : Array<string>,
  'totalTemplates' : bigint,
}
export interface Theme {
  'themeName' : string,
  'footerStyle' : string,
  'primaryColor' : string,
  'createdBy' : [] | [UserId],
  'headerDesign' : string,
  'fontFamily' : string,
  'secondaryColor' : string,
  'tableBorders' : boolean,
  'themeId' : ThemeId,
  'pageMargins' : string,
}
export type ThemeId = string;
export type Timestamp = bigint;
export type UserId = Principal;
export interface UserProfile {
  'id' : UserId,
  'country' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'role' : UserRole,
  'email' : string,
  'companyName' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'confirmPayment' : ActorMethod<[PaymentId, string], undefined>,
  'createDocument' : ActorMethod<[TemplateId, string, ThemeId], Document>,
  'createFormField' : ActorMethod<
    [
      TemplateId,
      string,
      string,
      string,
      Array<string>,
      boolean,
      [] | [string],
      bigint,
      bigint,
      string,
      string,
      boolean,
      [] | [{ 'conditionField' : string, 'conditionValue' : string }],
    ],
    FormField
  >,
  'createPlaceholder' : ActorMethod<
    [TemplateId, string, FieldId, string],
    Placeholder
  >,
  'createProfile' : ActorMethod<
    [string, string, string, string, string],
    UserProfile
  >,
  'createTemplate' : ActorMethod<
    [string, string, string, string, boolean],
    Template
  >,
  'createTheme' : ActorMethod<
    [string, string, string, string, string, string, boolean, string],
    Theme
  >,
  'deleteDocument' : ActorMethod<[DocumentId], undefined>,
  'deleteFormField' : ActorMethod<[FieldId], undefined>,
  'deletePlaceholder' : ActorMethod<[PlaceholderId], undefined>,
  'deleteTemplate' : ActorMethod<[TemplateId], undefined>,
  'deleteTheme' : ActorMethod<[ThemeId], undefined>,
  'demoteToUser' : ActorMethod<[UserId], undefined>,
  'getActiveTemplates' : ActorMethod<[], Array<Template>>,
  'getAllExports' : ActorMethod<[], Array<Export>>,
  'getAllPayments' : ActorMethod<[], Array<Payment>>,
  'getAllTemplates' : ActorMethod<[], Array<Template>>,
  'getAllThemes' : ActorMethod<[], Array<Theme>>,
  'getAllUsers' : ActorMethod<[], Array<UserProfile>>,
  'getAnalytics' : ActorMethod<
    [],
    {
      'totalUsers' : bigint,
      'totalRevenue' : bigint,
      'totalDownloads' : bigint,
      'totalDocuments' : bigint,
    }
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDocumentData' : ActorMethod<[DocumentId], Array<DocumentData>>,
  'getDocumentsByUser' : ActorMethod<[UserId], Array<Document>>,
  'getExportsByUser' : ActorMethod<[UserId], Array<Export>>,
  'getFieldsForTemplate' : ActorMethod<[TemplateId], Array<FormField>>,
  'getPaymentsByUser' : ActorMethod<[UserId], Array<Payment>>,
  'getPlaceholdersForTemplate' : ActorMethod<[TemplateId], Array<Placeholder>>,
  'getSeedStatus' : ActorMethod<[], TemplateSeedStatus>,
  'getTemplate' : ActorMethod<[TemplateId], [] | [Template]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'promoteToAdmin' : ActorMethod<[UserId], undefined>,
  'recordExport' : ActorMethod<
    [
      DocumentId,
      { 'pdf' : null } |
        { 'docx' : null } |
        { 'xlsx' : null },
      PaymentId,
    ],
    Export
  >,
  'recordPayment' : ActorMethod<[DocumentId, bigint, string], Payment>,
  'saveCallerUserProfile' : ActorMethod<
    [string, string, string, string, string],
    undefined
  >,
  'saveDocumentData' : ActorMethod<[DocumentId, FieldId, string], undefined>,
  'seedStandardTemplates' : ActorMethod<[], TemplateSeedResult>,
  'updateDocument' : ActorMethod<
    [DocumentId, string, ThemeId, { 'generated' : null } | { 'draft' : null }],
    undefined
  >,
  'updateFormField' : ActorMethod<
    [
      FieldId,
      string,
      string,
      Array<string>,
      boolean,
      [] | [string],
      bigint,
      bigint,
      string,
      string,
      boolean,
      [] | [{ 'conditionField' : string, 'conditionValue' : string }],
    ],
    undefined
  >,
  'updatePlaceholder' : ActorMethod<
    [PlaceholderId, string, FieldId, string],
    undefined
  >,
  'updateTemplate' : ActorMethod<
    [TemplateId, string, string, string, string, boolean],
    undefined
  >,
  'updateTheme' : ActorMethod<
    [ThemeId, string, string, string, string, string, string, boolean, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];