/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export type ThemeId = string;
export interface TemplateSeedStatus {
    totalThemes: bigint;
    seededTemplateNames: Array<string>;
    totalTemplates: bigint;
}
export interface FormField {
    fieldPlaceholder: string;
    order: bigint;
    templateId: TemplateId;
    fieldLabel: string;
    helpText: string;
    fieldWidth: bigint;
    visible: boolean;
    required: boolean;
    groupName: string;
    options: Array<string>;
    fieldType: Variant_textArea_multiSelect_numberField_textField_currency_checkbox_dateField_radio_percentage_dropdown;
    defaultValue?: string;
    fieldId: FieldId;
    condition?: {
        conditionField: string;
        conditionValue: string;
    };
}
export interface DocumentData {
    value: string;
    documentId: DocumentId;
    fieldId: FieldId;
}
export type TemplateId = string;
export type FieldId = string;
export type ExportId = string;
export interface Payment {
    status: Variant_pending_confirmed;
    userId: UserId;
    createdAt: Timestamp;
    currency: string;
    paymentId: PaymentId;
    documentId: DocumentId;
    amount: bigint;
    transactionId?: string;
}
export interface Placeholder {
    token: string;
    templateId: TemplateId;
    description: string;
    placeholderId: PlaceholderId;
    fieldId: FieldId;
}
export interface Document {
    status: Variant_generated_draft;
    title: string;
    templateId: TemplateId;
    userId: UserId;
    createdAt: Timestamp;
    updatedAt: Timestamp;
    documentId: DocumentId;
    themeId: ThemeId;
}
export interface Template {
    id: TemplateId;
    status: boolean;
    name: string;
    createdAt: Timestamp;
    createdBy: UserId;
    commodityType: string;
    description: string;
    category: string;
}
export type PlaceholderId = string;
export interface Export {
    exportId: ExportId;
    userId: UserId;
    downloadDate: Timestamp;
    paymentId: PaymentId;
    documentId: DocumentId;
    format: Variant_pdf_docx_xlsx;
}
export type UserId = Principal;
export type PaymentId = string;
export type DocumentId = string;
export interface Theme {
    themeName: string;
    footerStyle: string;
    primaryColor: string;
    createdBy?: UserId;
    headerDesign: string;
    fontFamily: string;
    secondaryColor: string;
    tableBorders: boolean;
    themeId: ThemeId;
    pageMargins: string;
}
export interface UserProfile {
    id: UserId;
    country: string;
    name: string;
    createdAt: Timestamp;
    role: UserRole;
    email: string;
    companyName: string;
    phone: string;
}
export interface TemplateSeedResult {
    templatesSkipped: bigint;
    themesCreated: bigint;
    templatesCreated: bigint;
    themesSkipped: bigint;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_generated_draft {
    generated = "generated",
    draft = "draft"
}
export enum Variant_pdf_docx_xlsx {
    pdf = "pdf",
    docx = "docx",
    xlsx = "xlsx"
}
export enum Variant_pending_confirmed {
    pending = "pending",
    confirmed = "confirmed"
}
export enum Variant_textArea_multiSelect_numberField_textField_currency_checkbox_dateField_radio_percentage_dropdown {
    textArea = "textArea",
    multiSelect = "multiSelect",
    numberField = "numberField",
    textField = "textField",
    currency = "currency",
    checkbox = "checkbox",
    dateField = "dateField",
    radio = "radio",
    percentage = "percentage",
    dropdown = "dropdown"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    confirmPayment(paymentId: PaymentId, transactionId: string): Promise<void>;
    createDocument(templateId: TemplateId, title: string, themeId: ThemeId): Promise<Document>;
    createFormField(templateId: TemplateId, fieldLabel: string, fieldPlaceholder: string, _fieldType: string, options: Array<string>, required: boolean, defaultValue: string | null, order: bigint, fieldWidth: bigint, helpText: string, groupName: string, visible: boolean, condition: {
        conditionField: string;
        conditionValue: string;
    } | null): Promise<FormField>;
    createPlaceholder(templateId: TemplateId, token: string, fieldId: FieldId, description: string): Promise<Placeholder>;
    createProfile(name: string, email: string, companyName: string, country: string, phone: string): Promise<UserProfile>;
    createTemplate(name: string, category: string, commodityType: string, description: string, status: boolean): Promise<Template>;
    createTheme(themeName: string, fontFamily: string, primaryColor: string, secondaryColor: string, headerDesign: string, footerStyle: string, tableBorders: boolean, pageMargins: string): Promise<Theme>;
    deleteDocument(documentId: DocumentId): Promise<void>;
    deleteFormField(fieldId: FieldId): Promise<void>;
    deletePlaceholder(placeholderId: PlaceholderId): Promise<void>;
    deleteTemplate(id: TemplateId): Promise<void>;
    deleteTheme(themeId: ThemeId): Promise<void>;
    demoteToUser(user: UserId): Promise<void>;
    getActiveTemplates(): Promise<Array<Template>>;
    getAllExports(): Promise<Array<Export>>;
    getAllPayments(): Promise<Array<Payment>>;
    getAllTemplates(): Promise<Array<Template>>;
    getAllThemes(): Promise<Array<Theme>>;
    getAllUsers(): Promise<Array<UserProfile>>;
    getAnalytics(): Promise<{
        totalUsers: bigint;
        totalRevenue: bigint;
        totalDownloads: bigint;
        totalDocuments: bigint;
    }>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDocumentData(documentId: DocumentId): Promise<Array<DocumentData>>;
    getDocumentsByUser(userId: UserId): Promise<Array<Document>>;
    getExportsByUser(userId: UserId): Promise<Array<Export>>;
    getFieldsForTemplate(templateId: TemplateId): Promise<Array<FormField>>;
    getPaymentsByUser(userId: UserId): Promise<Array<Payment>>;
    getPlaceholdersForTemplate(templateId: TemplateId): Promise<Array<Placeholder>>;
    getSeedStatus(): Promise<TemplateSeedStatus>;
    getTemplate(id: TemplateId): Promise<Template | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    promoteToAdmin(user: UserId): Promise<void>;
    recordExport(documentId: DocumentId, format: Variant_pdf_docx_xlsx, paymentId: PaymentId): Promise<Export>;
    recordPayment(documentId: DocumentId, amount: bigint, currency: string): Promise<Payment>;
    saveCallerUserProfile(name: string, email: string, companyName: string, country: string, phone: string): Promise<void>;
    saveDocumentData(documentId: DocumentId, fieldId: FieldId, value: string): Promise<void>;
    seedStandardTemplates(): Promise<TemplateSeedResult>;
    updateDocument(documentId: DocumentId, title: string, themeId: ThemeId, status: Variant_generated_draft): Promise<void>;
    updateFormField(fieldId: FieldId, fieldLabel: string, fieldPlaceholder: string, options: Array<string>, required: boolean, defaultValue: string | null, order: bigint, fieldWidth: bigint, helpText: string, groupName: string, visible: boolean, condition: {
        conditionField: string;
        conditionValue: string;
    } | null): Promise<void>;
    updatePlaceholder(placeholderId: PlaceholderId, token: string, fieldId: FieldId, description: string): Promise<void>;
    updateTemplate(id: TemplateId, name: string, category: string, commodityType: string, description: string, status: boolean): Promise<void>;
    updateTheme(themeId: ThemeId, themeName: string, fontFamily: string, primaryColor: string, secondaryColor: string, headerDesign: string, footerStyle: string, tableBorders: boolean, pageMargins: string): Promise<void>;
}
import type { Document as _Document, DocumentId as _DocumentId, Export as _Export, ExportId as _ExportId, FieldId as _FieldId, FormField as _FormField, Payment as _Payment, PaymentId as _PaymentId, Template as _Template, TemplateId as _TemplateId, Theme as _Theme, ThemeId as _ThemeId, Timestamp as _Timestamp, UserId as _UserId, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async confirmPayment(arg0: PaymentId, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.confirmPayment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.confirmPayment(arg0, arg1);
            return result;
        }
    }
    async createDocument(arg0: TemplateId, arg1: string, arg2: ThemeId): Promise<Document> {
        if (this.processError) {
            try {
                const result = await this.actor.createDocument(arg0, arg1, arg2);
                return from_candid_Document_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDocument(arg0, arg1, arg2);
            return from_candid_Document_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async createFormField(arg0: TemplateId, arg1: string, arg2: string, arg3: string, arg4: Array<string>, arg5: boolean, arg6: string | null, arg7: bigint, arg8: bigint, arg9: string, arg10: string, arg11: boolean, arg12: {
        conditionField: string;
        conditionValue: string;
    } | null): Promise<FormField> {
        if (this.processError) {
            try {
                const result = await this.actor.createFormField(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_opt_n6(this._uploadFile, this._downloadFile, arg6), arg7, arg8, arg9, arg10, arg11, to_candid_opt_n7(this._uploadFile, this._downloadFile, arg12));
                return from_candid_FormField_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createFormField(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_opt_n6(this._uploadFile, this._downloadFile, arg6), arg7, arg8, arg9, arg10, arg11, to_candid_opt_n7(this._uploadFile, this._downloadFile, arg12));
            return from_candid_FormField_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async createPlaceholder(arg0: TemplateId, arg1: string, arg2: FieldId, arg3: string): Promise<Placeholder> {
        if (this.processError) {
            try {
                const result = await this.actor.createPlaceholder(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPlaceholder(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createProfile(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.createProfile(arg0, arg1, arg2, arg3, arg4);
                return from_candid_UserProfile_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProfile(arg0, arg1, arg2, arg3, arg4);
            return from_candid_UserProfile_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async createTemplate(arg0: string, arg1: string, arg2: string, arg3: string, arg4: boolean): Promise<Template> {
        if (this.processError) {
            try {
                const result = await this.actor.createTemplate(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTemplate(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async createTheme(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: boolean, arg7: string): Promise<Theme> {
        if (this.processError) {
            try {
                const result = await this.actor.createTheme(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return from_candid_Theme_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTheme(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return from_candid_Theme_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteDocument(arg0: DocumentId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDocument(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDocument(arg0);
            return result;
        }
    }
    async deleteFormField(arg0: FieldId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFormField(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFormField(arg0);
            return result;
        }
    }
    async deletePlaceholder(arg0: PlaceholderId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePlaceholder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePlaceholder(arg0);
            return result;
        }
    }
    async deleteTemplate(arg0: TemplateId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTemplate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTemplate(arg0);
            return result;
        }
    }
    async deleteTheme(arg0: ThemeId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTheme(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTheme(arg0);
            return result;
        }
    }
    async demoteToUser(arg0: UserId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.demoteToUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.demoteToUser(arg0);
            return result;
        }
    }
    async getActiveTemplates(): Promise<Array<Template>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveTemplates();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveTemplates();
            return result;
        }
    }
    async getAllExports(): Promise<Array<Export>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllExports();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllExports();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPayments(): Promise<Array<Payment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPayments();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPayments();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTemplates(): Promise<Array<Template>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTemplates();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTemplates();
            return result;
        }
    }
    async getAllThemes(): Promise<Array<Theme>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllThemes();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllThemes();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUsers(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAnalytics(): Promise<{
        totalUsers: bigint;
        totalRevenue: bigint;
        totalDownloads: bigint;
        totalDocuments: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnalytics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnalytics();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDocumentData(arg0: DocumentId): Promise<Array<DocumentData>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDocumentData(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDocumentData(arg0);
            return result;
        }
    }
    async getDocumentsByUser(arg0: UserId): Promise<Array<Document>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDocumentsByUser(arg0);
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDocumentsByUser(arg0);
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExportsByUser(arg0: UserId): Promise<Array<Export>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExportsByUser(arg0);
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExportsByUser(arg0);
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFieldsForTemplate(arg0: TemplateId): Promise<Array<FormField>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFieldsForTemplate(arg0);
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFieldsForTemplate(arg0);
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPaymentsByUser(arg0: UserId): Promise<Array<Payment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPaymentsByUser(arg0);
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPaymentsByUser(arg0);
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlaceholdersForTemplate(arg0: TemplateId): Promise<Array<Placeholder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlaceholdersForTemplate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlaceholdersForTemplate(arg0);
            return result;
        }
    }
    async getSeedStatus(): Promise<TemplateSeedStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getSeedStatus();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSeedStatus();
            return result;
        }
    }
    async getTemplate(arg0: TemplateId): Promise<Template | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTemplate(arg0);
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTemplate(arg0);
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async promoteToAdmin(arg0: UserId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.promoteToAdmin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.promoteToAdmin(arg0);
            return result;
        }
    }
    async recordExport(arg0: DocumentId, arg1: Variant_pdf_docx_xlsx, arg2: PaymentId): Promise<Export> {
        if (this.processError) {
            try {
                const result = await this.actor.recordExport(arg0, to_candid_variant_n34(this._uploadFile, this._downloadFile, arg1), arg2);
                return from_candid_Export_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordExport(arg0, to_candid_variant_n34(this._uploadFile, this._downloadFile, arg1), arg2);
            return from_candid_Export_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async recordPayment(arg0: DocumentId, arg1: bigint, arg2: string): Promise<Payment> {
        if (this.processError) {
            try {
                const result = await this.actor.recordPayment(arg0, arg1, arg2);
                return from_candid_Payment_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordPayment(arg0, arg1, arg2);
            return from_candid_Payment_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async saveDocumentData(arg0: DocumentId, arg1: FieldId, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveDocumentData(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveDocumentData(arg0, arg1, arg2);
            return result;
        }
    }
    async seedStandardTemplates(): Promise<TemplateSeedResult> {
        if (this.processError) {
            try {
                const result = await this.actor.seedStandardTemplates();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedStandardTemplates();
            return result;
        }
    }
    async updateDocument(arg0: DocumentId, arg1: string, arg2: ThemeId, arg3: Variant_generated_draft): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDocument(arg0, arg1, arg2, to_candid_variant_n35(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDocument(arg0, arg1, arg2, to_candid_variant_n35(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async updateFormField(arg0: FieldId, arg1: string, arg2: string, arg3: Array<string>, arg4: boolean, arg5: string | null, arg6: bigint, arg7: bigint, arg8: string, arg9: string, arg10: boolean, arg11: {
        conditionField: string;
        conditionValue: string;
    } | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFormField(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n6(this._uploadFile, this._downloadFile, arg5), arg6, arg7, arg8, arg9, arg10, to_candid_opt_n7(this._uploadFile, this._downloadFile, arg11));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFormField(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n6(this._uploadFile, this._downloadFile, arg5), arg6, arg7, arg8, arg9, arg10, to_candid_opt_n7(this._uploadFile, this._downloadFile, arg11));
            return result;
        }
    }
    async updatePlaceholder(arg0: PlaceholderId, arg1: string, arg2: FieldId, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePlaceholder(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePlaceholder(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateTemplate(arg0: TemplateId, arg1: string, arg2: string, arg3: string, arg4: string, arg5: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTemplate(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTemplate(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async updateTheme(arg0: ThemeId, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string, arg7: boolean, arg8: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTheme(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTheme(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            return result;
        }
    }
}
function from_candid_Document_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Document): Document {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_Export_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Export): Export {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_FormField_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FormField): FormField {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Payment_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Payment): Payment {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_Theme_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Theme): Theme {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        conditionField: string;
        conditionValue: string;
    }]): {
    conditionField: string;
    conditionValue: string;
} | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserId]): UserId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Template]): Template | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    country: string;
    name: string;
    createdAt: _Timestamp;
    role: _UserRole;
    email: string;
    companyName: string;
    phone: string;
}): {
    id: UserId;
    country: string;
    name: string;
    createdAt: Timestamp;
    role: UserRole;
    email: string;
    companyName: string;
    phone: string;
} {
    return {
        id: value.id,
        country: value.country,
        name: value.name,
        createdAt: value.createdAt,
        role: from_candid_UserRole_n15(_uploadFile, _downloadFile, value.role),
        email: value.email,
        companyName: value.companyName,
        phone: value.phone
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    themeName: string;
    footerStyle: string;
    primaryColor: string;
    createdBy: [] | [_UserId];
    headerDesign: string;
    fontFamily: string;
    secondaryColor: string;
    tableBorders: boolean;
    themeId: _ThemeId;
    pageMargins: string;
}): {
    themeName: string;
    footerStyle: string;
    primaryColor: string;
    createdBy?: UserId;
    headerDesign: string;
    fontFamily: string;
    secondaryColor: string;
    tableBorders: boolean;
    themeId: ThemeId;
    pageMargins: string;
} {
    return {
        themeName: value.themeName,
        footerStyle: value.footerStyle,
        primaryColor: value.primaryColor,
        createdBy: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.createdBy)),
        headerDesign: value.headerDesign,
        fontFamily: value.fontFamily,
        secondaryColor: value.secondaryColor,
        tableBorders: value.tableBorders,
        themeId: value.themeId,
        pageMargins: value.pageMargins
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    exportId: _ExportId;
    userId: _UserId;
    downloadDate: _Timestamp;
    paymentId: _PaymentId;
    documentId: _DocumentId;
    format: {
        pdf: null;
    } | {
        docx: null;
    } | {
        xlsx: null;
    };
}): {
    exportId: ExportId;
    userId: UserId;
    downloadDate: Timestamp;
    paymentId: PaymentId;
    documentId: DocumentId;
    format: Variant_pdf_docx_xlsx;
} {
    return {
        exportId: value.exportId,
        userId: value.userId,
        downloadDate: value.downloadDate,
        paymentId: value.paymentId,
        documentId: value.documentId,
        format: from_candid_variant_n23(_uploadFile, _downloadFile, value.format)
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: {
        pending: null;
    } | {
        confirmed: null;
    };
    userId: _UserId;
    createdAt: _Timestamp;
    currency: string;
    paymentId: _PaymentId;
    documentId: _DocumentId;
    amount: bigint;
    transactionId: [] | [string];
}): {
    status: Variant_pending_confirmed;
    userId: UserId;
    createdAt: Timestamp;
    currency: string;
    paymentId: PaymentId;
    documentId: DocumentId;
    amount: bigint;
    transactionId?: string;
} {
    return {
        status: from_candid_variant_n27(_uploadFile, _downloadFile, value.status),
        userId: value.userId,
        createdAt: value.createdAt,
        currency: value.currency,
        paymentId: value.paymentId,
        documentId: value.documentId,
        amount: value.amount,
        transactionId: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.transactionId))
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: {
        generated: null;
    } | {
        draft: null;
    };
    title: string;
    templateId: _TemplateId;
    userId: _UserId;
    createdAt: _Timestamp;
    updatedAt: _Timestamp;
    documentId: _DocumentId;
    themeId: _ThemeId;
}): {
    status: Variant_generated_draft;
    title: string;
    templateId: TemplateId;
    userId: UserId;
    createdAt: Timestamp;
    updatedAt: Timestamp;
    documentId: DocumentId;
    themeId: ThemeId;
} {
    return {
        status: from_candid_variant_n5(_uploadFile, _downloadFile, value.status),
        title: value.title,
        templateId: value.templateId,
        userId: value.userId,
        createdAt: value.createdAt,
        updatedAt: value.updatedAt,
        documentId: value.documentId,
        themeId: value.themeId
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fieldPlaceholder: string;
    order: bigint;
    templateId: _TemplateId;
    fieldLabel: string;
    helpText: string;
    fieldWidth: bigint;
    visible: boolean;
    required: boolean;
    groupName: string;
    options: Array<string>;
    fieldType: {
        textArea: null;
    } | {
        multiSelect: null;
    } | {
        numberField: null;
    } | {
        textField: null;
    } | {
        currency: null;
    } | {
        checkbox: null;
    } | {
        dateField: null;
    } | {
        radio: null;
    } | {
        percentage: null;
    } | {
        dropdown: null;
    };
    defaultValue: [] | [string];
    fieldId: _FieldId;
    condition: [] | [{
            conditionField: string;
            conditionValue: string;
        }];
}): {
    fieldPlaceholder: string;
    order: bigint;
    templateId: TemplateId;
    fieldLabel: string;
    helpText: string;
    fieldWidth: bigint;
    visible: boolean;
    required: boolean;
    groupName: string;
    options: Array<string>;
    fieldType: Variant_textArea_multiSelect_numberField_textField_currency_checkbox_dateField_radio_percentage_dropdown;
    defaultValue?: string;
    fieldId: FieldId;
    condition?: {
        conditionField: string;
        conditionValue: string;
    };
} {
    return {
        fieldPlaceholder: value.fieldPlaceholder,
        order: value.order,
        templateId: value.templateId,
        fieldLabel: value.fieldLabel,
        helpText: value.helpText,
        fieldWidth: value.fieldWidth,
        visible: value.visible,
        required: value.required,
        groupName: value.groupName,
        options: value.options,
        fieldType: from_candid_variant_n10(_uploadFile, _downloadFile, value.fieldType),
        defaultValue: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.defaultValue)),
        fieldId: value.fieldId,
        condition: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.condition))
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    textArea: null;
} | {
    multiSelect: null;
} | {
    numberField: null;
} | {
    textField: null;
} | {
    currency: null;
} | {
    checkbox: null;
} | {
    dateField: null;
} | {
    radio: null;
} | {
    percentage: null;
} | {
    dropdown: null;
}): Variant_textArea_multiSelect_numberField_textField_currency_checkbox_dateField_radio_percentage_dropdown {
    return "textArea" in value ? Variant_textArea_multiSelect_numberField_textField_currency_checkbox_dateField_radio_percentage_dropdown.textArea : "multiSelect" in value ? Variant_textArea_multiSelect_numberField_textField_currency_checkbox_dateField_radio_percentage_dropdown.multiSelect : "numberField" in value ? Variant_textArea_multiSelect_numberField_textField_currency_checkbox_dateField_radio_percentage_dropdown.numberField : "textField" in value ? Variant_textArea_multiSelect_numberField_textField_currency_checkbox_dateField_radio_percentage_dropdown.textField : "currency" in value ? Variant_textArea_multiSelect_numberField_textField_currency_checkbox_dateField_radio_percentage_dropdown.currency : "checkbox" in value ? Variant_textArea_multiSelect_numberField_textField_currency_checkbox_dateField_radio_percentage_dropdown.checkbox : "dateField" in value ? Variant_textArea_multiSelect_numberField_textField_currency_checkbox_dateField_radio_percentage_dropdown.dateField : "radio" in value ? Variant_textArea_multiSelect_numberField_textField_currency_checkbox_dateField_radio_percentage_dropdown.radio : "percentage" in value ? Variant_textArea_multiSelect_numberField_textField_currency_checkbox_dateField_radio_percentage_dropdown.percentage : "dropdown" in value ? Variant_textArea_multiSelect_numberField_textField_currency_checkbox_dateField_radio_percentage_dropdown.dropdown : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pdf: null;
} | {
    docx: null;
} | {
    xlsx: null;
}): Variant_pdf_docx_xlsx {
    return "pdf" in value ? Variant_pdf_docx_xlsx.pdf : "docx" in value ? Variant_pdf_docx_xlsx.docx : "xlsx" in value ? Variant_pdf_docx_xlsx.xlsx : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    confirmed: null;
}): Variant_pending_confirmed {
    return "pending" in value ? Variant_pending_confirmed.pending : "confirmed" in value ? Variant_pending_confirmed.confirmed : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    generated: null;
} | {
    draft: null;
}): Variant_generated_draft {
    return "generated" in value ? Variant_generated_draft.generated : "draft" in value ? Variant_generated_draft.draft : value;
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Export>): Array<Export> {
    return value.map((x)=>from_candid_Export_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Payment>): Array<Payment> {
    return value.map((x)=>from_candid_Payment_n25(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Theme>): Array<Theme> {
    return value.map((x)=>from_candid_Theme_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfile>): Array<UserProfile> {
    return value.map((x)=>from_candid_UserProfile_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Document>): Array<Document> {
    return value.map((x)=>from_candid_Document_n3(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FormField>): Array<FormField> {
    return value.map((x)=>from_candid_FormField_n8(_uploadFile, _downloadFile, x));
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    conditionField: string;
    conditionValue: string;
} | null): [] | [{
        conditionField: string;
        conditionValue: string;
    }] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_pdf_docx_xlsx): {
    pdf: null;
} | {
    docx: null;
} | {
    xlsx: null;
} {
    return value == Variant_pdf_docx_xlsx.pdf ? {
        pdf: null
    } : value == Variant_pdf_docx_xlsx.docx ? {
        docx: null
    } : value == Variant_pdf_docx_xlsx.xlsx ? {
        xlsx: null
    } : value;
}
function to_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_generated_draft): {
    generated: null;
} | {
    draft: null;
} {
    return value == Variant_generated_draft.generated ? {
        generated: null
    } : value == Variant_generated_draft.draft ? {
        draft: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
